language: haskell
before_install:
env:
 - GHCVER=8.6.5 CABALVER=3.2
 - GHCVER=8.8.4 CABALVER=3.2
 - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - cabal --version

install:
 - cabal update

script:
 - cabal build
 - cabal test
